
import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    container:{
      backgroundColor:'#E5E5E5',
      flex:1,
      alignItems:'center',
      justifyContent:'center',
    },
    containerUser:{
      width:'90%',
      height:'60%',
      justifyContent:'center',
      alignItems:'center',
      marginBottom:320
    },
    txt:{
         fontSize:34,
         marginBottom:10,
         color:'#000'
    },
    avatarUser:{
      alignItems:'center',
      width:128,
      height:129,
      backgroundColor:'#ffff',
      justifyContent:'center',
      marginVertical:60
    },
    imgLogo:{
      justifyContent:'center',
      backgroundColor:'grey',
      width:114,
      height:114,
      borderRadius:80
    },
    editProfile:{
      backgroundColor:'#304FFE',
      width:'80%',
      padding:15,
      borderRadius:7,
      alignItems:'center',
      marginVertical:15,
      marginTop:30
    },
    infoUser:{
      marginRight:180
    },
    descripInfoUser:{
      color:'#000',
      fontSize:15,
      fontWeight:'700'
    },
    logOut:{
      backgroundColor:'#ffff',
      width:'80%',
      padding:15,
      borderRadius:7,
      alignItems:'center',
      borderWidth:1,
      borderColor:'#000',

    },
    input:{
      width:'80%',
      backgroundColor:'#ffff',
      borderWidth:1,
      borderColor:'black',
      borderRadius:5,
      marginVertical:10
    }
  });